name: Build and deploy

on:
  push:
    branches: [ master ]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # - run: yarn install --pure-lockfile
    - run: mkdir build
    - run: echo 'walrus' > build/index.html
    - uses: amondnet/now-deployment@v2.0.2
      with:
        zeit-token: ${{ secrets.ZEIT_NOW_TOKEN }}
        now-project-id: ${{ secrets.ZEIT_NOW_PROJECT_ID }}
        now-org-id: ${{ secrets.ZEIT_NOW_ORG_ID }}
