name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn generate-templates
      - run: yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
          CI: "false"
      - run: npx now --prod -t ${{ secrets.ZEIT_NOW_TOKEN }}
        working-directory: forest
        env:
          NOW_ORG_ID: ${{ secrets.ZEIT_NOW_ORG_ID }}
          NOW_PROJECT_ID: ${{ secrets.ZEIT_NOW_PROJECT_ID }}
